### ISSUE TITLE
Installation Issue: Linking CXX executable sapphire

### ISSUE THREAD

**Issue by rkelmar** [phScholz/SAPPHIRE#100] opened 2020-07-15 17:02 UTC
When I run build.sh on Linux system I get the error

 Linking CXX executable sapphire
CMakeFiles/sapphire.dir/Modules/Module_OldSapphire.cpp.o: In function `Module_OldSapphire::parseCommandLineForDecay(std::vector<std::string, std::allocator<std::string> >&, int&, int&, double&, int&, double&, double&, int&)':
Module_OldSapphire.cpp:(.text+0x513f): undefined reference to `TString::TString(std::string const&)'
Module_OldSapphire.cpp:(.text+0x5242): undefined reference to `TString::TString(std::string const&)'
Module_OldSapphire.cpp:(.text+0x52de): undefined reference to `TString::TString(std::string const&)'
Module_OldSapphire.cpp:(.text+0x5587): undefined reference to `TString::TString(std::string const&)'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libGraf.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_mutate(unsigned long, unsigned long, wchar_t const*, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libTreePlayer.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libHist.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libGraf.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_assign(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libGraf.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libTreePlayer.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libHist.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libROOTDataFrame.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libHist.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::invalid_argument::invalid_argument(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libGraf.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libROOTDataFrame.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libGraf.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_construct(unsigned long, wchar_t)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libROOTDataFrame.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::domain_error::domain_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libROOTDataFrame.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libRIO.so: undefined reference to `std::out_of_range::out_of_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libROOTDataFrame.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libtbb.so.2: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/afs/crc.nd.edu/user/n/nsl/nuclear/x86_64_linux_el6/install/root_v6.14.06/lib/libCore.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [src/sapphire] Error 1
make[1]: *** [src/CMakeFiles/sapphire.dir/all] Error 2
make: *** [all] Error 2

**Comment by phScholz** [comment] 2020-07-19 07:13
Apparently, this is a bug resulting from incompatibilities with the root version 6.14. due to the TString::TString(std::string const&) method.

Workaround: use an older root version.

TODO: Fix incompatibility with root 6.14.

**Comment by phScholz** [comment] 2020-07-19 07:58
It seems like the problem is fixed by explicitly setting the CXX compiler for Cmake to g++ instead of gcc in the CMakeLists.txt files.

Problem should be solved now.

**Closed** 2020-08-31 15:12 UTC
Labels: bug
